name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
        registry-url: https://registry.npmjs.org/
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: npm publish --access=public    
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}